### ISSUE TITLE
Suitable for supporting server and WebAssembly modes like. net 8

### ISSUE THREAD

**Issue by anan1213095357** [tryphotino/photino.Blazor#100]
System.NotSupportedException:“Cannot supply a component of type 'Photino.Blazor.Sample.Pages.Index' because the current platform does not support the render mode 'Microsoft.AspNetCore.Components.Web.InteractiveWebAssemblyRenderMode'.”

**Comment by ivanjx** [comment]
everything would be run and rendered on the local computer (client) so it does not make sense to add server mode and webassembly mode. the c# code will be run directly on dotnet runtime instead of the wasm runtime.

**Comment by MikeYeager** [comment]
Agreed. Concerning web assembly, as ivanjx said, you're already running on the full .NET runtime, so why would we run the .NET runtime in WASM. Unless we're not understanding something. Thank you for the suggestion.

**Comment by anan1213095357** [comment]
> Agreed. Concerning web assembly, as ivanjx said, you're already running on the full .NET runtime, so why would we run the .NET runtime in WASM. Unless we're not understanding something. Thank you for the suggestion.

I understand your suggestion, because. net8 is a joint rendering mode that can support each other. The reason why I am persistent in pursuing wasm is because some elements and events in the dom, such as mousemove, are not something that servers like mousemove can do

**Comment by anan1213095357** [comment]
> everything would be run and rendered on the local computer (client) so it does not make sense to add server mode and webassembly mode. the c# code will be run directly on dotnet runtime instead of the wasm runtime.

I understand your suggestion, because. net8 is a joint rendering mode that can support each other. The reason why I am persistent in pursuing wasm is because some elements and events in the dom, such as mousemove, are not something that servers like mousemove can do
