### ISSUE TITLE
"Building" questions

### ISSUE THREAD

**Issue by MeestorX** [tryphotino/photino.Blazor#102]
Very cool project.
I've looked and searched as much as I can, so my apologies if this is documented somewhere?

I'm using VSCode on MacOS to create Photino Blazor apps.
Using the standard dotnet CLI commands to build the app don't seem to work as expected, comparing this to a Blazor Hybrid workload.
`dotnet build` should create a Release version of the application, packaged into an `.app` file. I can't see how to create an `.app` file.
`dotnet publish` should create a Release version of the application, packaged into a `.pkg` (MacOS installer) file.

Does the `dotnet build` parameter `--self-contained` work?
Any way to make a single-file build?

**Comment by MikeYeager** [comment]
@philippjbauer is planning on creating some documentation around distribution strategies on all 3 platforms.

**Comment by philippjbauer** [comment]
@MeestorX 

The guide for publishing on all platforms is available as a sample in the Photino.Samples repository as a separate project. It includes a publish script and packaging templates that can be adapted for your specific situation.

Currently only available in the debug branch (as of 03/19/2024), lets find the rough edges together! :)
https://github.com/tryphotino/photino.Samples/tree/debug/Photino.PublishPhotino
