### ISSUE TITLE
css/bootstrap sizing is messed up

### ISSUE THREAD

**Issue by MeestorX** [tryphotino/photino.Blazor#103]
Bootstrap css classes like "col-6" don't size properly. col-6 should produce an element that's 50% of the width of the viewport. 
The horizontal percentage css is squished to have almost no width, regardless of the viewport width.

**Comment by MikeYeager** [comment]
@MeestorX That is completely under the control of the browser control, so it's hard to imagine that we could have any influence over that. Perhaps you can create a simple example and share the repo so we can see the problem more clearly. We're happy to take a look and see if it's something we can address.

**Comment by MeestorX** [comment]
Thank you for your reply. Scaling is also different, but that's not the main issue. Look at the "Some Data" spans.
On Maui/Blazor:
![image](https://github.com/tryphotino/photino.Blazor/assets/29129658/d939dd34-d568-49d2-aa97-9acc1742406e)

Photino:
![image](https://github.com/tryphotino/photino.Blazor/assets/29129658/b6b32fa8-0a41-4068-8bf7-a428edf493e0)

Larger Maui/Blazor:
![image](https://github.com/tryphotino/photino.Blazor/assets/29129658/18587ad5-c119-46d8-88f5-abd573372e9b)

Photino:
![image](https://github.com/tryphotino/photino.Blazor/assets/29129658/77eb5c1b-00a3-4beb-8f9e-cbb6e7111dee)

**Comment by MeestorX** [comment]
```
@page "/"

<h1 style="text-align:center">TEST</h1>
<div class="container-fluid">
    <div class="row">
        <label for="devip" class="col-2 col-form-label-lg">TextInput 1</label>
        <label for="devport" class="col-2 col-form-label-lg">TextInput 2</label>
    </div>
    <input type="text" id="devip" placeholder="TextInput 1" class="col-2 col-form-control-lg"> 
    <input type="text" id="devport" placeholder="TextInput 2" class="col-2 col-form-control-lg">
    <button class="col-1 btn btn-primary">Start</button>
    <button class="col-1 btn btn-primary">Stop</button>

    <div class="row">
        <h3>Some Data:</h3>
        <div class="row">
            <span id="url" class="col-5 input-group-text form-control-lg m-2" style="font-weight:bold; font-size:large;"></span>
            <span id="nGrokIp" class="col-5 input-group-text form-control-lg m-2" style="font-weight:bold; font-size:large;"></span>
        </div>
    </div>
</div>
<div class="container-fluid" style="height:50vh">
    <div>
        <h2>Output:</h2>
    </div>
    <div style="font-family:menlo; white-space: pre-wrap; overflow:scroll; height:50%; border:thin solid black">
        Some Sample Text
    </div>
    <div>
        <h2>Errors:</h2>
    </div>
    <div style="font-family:menlo; white-space: pre-wrap; overflow:scroll; height:20%; border:thin solid black">
       Some Sample Errors
    </div>
</div>
```

**Comment by MikeYeager** [comment]
Closed due to inactivity.
