### ISSUE TITLE
New version (2.7.0) not resolving paths to localhost as it did in previous versions (2.6.0)

### ISSUE THREAD

**Issue by grofit** [tryphotino/photino.Blazor#107]
From what I can tell it looks like the new version may be handling paths differently, as I can see its trying to load things, but in the previous version I would load things on the index.html like `<link href="css/bulma.css" rel="stylesheet" />`

![Example Folder Layout](https://github.com/tryphotino/photino.Blazor/assets/927201/9ac30e06-b53f-4dfc-856b-d4469b9d89c3)

However now it seems to be trying to load these resources from the root of the disk, i.e my code is on my `E` drive and its trying to resolve the above as `E:/css/bulma.css` which doesnt exist, in the old version it would try and load from `http://localhost/css/bulma.css`.

When running in the previous version (2.6.0) I see this in the console logs:
> Photino.NET: "ProjectName".Load(E:\Code\projects\ProjectName\src\ProjectName\bin\Debug\net8.0\wwwroot\_content\ProjectName\index.html)
Photino.NET: "ProjectName".Load(file:///E:/Code/projects/ProjectName/src/ProjectName/bin/Debug/net8.0/wwwroot/_content/ProjectName/index.html)
Photino.NET: "ProjectName".Load(http://localhost/)

On new version (2.7.0) I get:
> Photino.NET: "ProjectName".Load(E:\Code\projects\ProjectName\src\ProjectName\bin\Debug\net8.0\wwwroot\_content\ProjectName\index.html)
Photino.NET: "ProjectName".Load(file:///E:/Code/projects/ProjectName/src/ProjectName/bin/Debug/net8.0/wwwroot/_content/ProjectName/index.html)
Photino.NET: "ProjectName".Load(file:///E:/Code/projects/ProjectName/src/ProjectName/bin/Debug/net8.0/wwwroot/_content/ProjectName/index.html)

So its definitely handling stuff differently internally from what I can tell.

Here is my setup code:
```csharp
public void SetupWindow(PhotinoBlazorApp app)
    {
        var rootIndexPage = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "wwwroot\\_content\\ProjectName\\index.html");
        var appLauncher = app.MainWindow
            .SetTitle("ProjectName")
            
#if DEBUG
            .SetLogVerbosity(3)
#else
            .SetLogVerbosity(0)
#endif
            
            .SetSize(1920, 1080)
            .SetUseOsDefaultSize(false)
            .SetIconFile("favicon.ico");
#if DEBUG
        appLauncher = appLauncher.SetDevToolsEnabled(true);
#else
        appLauncher = appLauncher.SetDevToolsEnabled(false);
        appLauncher = appLauncher.SetContextMenuEnabled(false);
#endif
        appLauncher.Load(rootIndexPage);
    }
```

**Comment by philippjbauer** [comment]
Hi @grofit! We're not quite following what you are trying to achieve. It seems like you are trying to load the UI for a Blazor app like you would using the Photino.NET way. Photino.Blazor and Photino.NET have different loading mechanisms. Please review the [simple Blazor sample here](https://github.com/tryphotino/photino.Blazor/blob/master/Samples/Photino.Blazor.Sample/Program.cs) for how to use the PhotinoBlazor package. If you didn't mean to use Blazor, refer to the Photino.NET sample in https://github.com/tryphotino/photino.Samples

If you are instead trying to navigate to another location in Blazor you would want to use `app.WindowManager.Navigate(rootIndexPage);` instead. From what we can tell though is that this is initialization code and you would not use Load in this context using a Photino.Blazor app.

If we're way off track here, please provide us with a link to your code if possible so we can look at it in context / are able to run it on our side.

**Comment by grofit** [comment]
I am using Photino Blazor I just have a lot of custom setup and I have to do things in a bit more of a lifecycle manner so the blazor setup bit happens later on, maybe its not done the correct way but its worked fine up until now.

Here is one of the main projects which uses it and has a very similar setup method.

https://github.com/strem-app/strem/blob/main/src/Strem/Application/BlazorBootstrapper.cs

If you were to clone `main` of that repo, then run it, it would run fine everything resolves as expected, then if you bump the dependency `Photino.Blazor` to the newer version and run again it will exhibit the problem I show above.

**Comment by grofit** [comment]
I have removed the `Load(rootPage)` bit and it functions as expected, so happy to close this issue if there is no problem but it still seems odd that it used to work but no longer does so your choice if you deem it worth looking into more or not.

**Comment by philippjbauer** [comment]
We just looked at your application and came to the same conclusion while testing it.

Cool app idea btw, I'll check it out more closely later
