### ISSUE TITLE
Close windows event do not work

### ISSUE THREAD

**Issue by oceanworldclient** [tryphotino/photino.Blazor#112]
Platform: MacOS arm64

code
`
        AppDomain.CurrentDomain.ProcessExit += (sender, args) =>
        {
            // not work
            Console.WriteLine("closing");
        };

        app.MainWindow.RegisterWindowClosingHandler(((sender, eventArgs) =>
        {
             // not work
            Console.WriteLine("closing win");
        }));
`

PublishType: WinExe

Close Windows (Click close button) or Quit from Top Bar Menu. Exit event do not trigger

**Comment by philippjbauer** [comment]
@oceanworldclient This issue is fixed and will be included in the next release!
