### ISSUE TITLE
centos 7 not work after Photino.NET 2.3.0

### ISSUE THREAD

**Issue by kingsonchan** [tryphotino/photino.Blazor#114]
I found that the latest version the supported in centos7 is Photino.NET 2.3.0, after this version, it will say libPhotino.Native: cannot open shared object file: No such file or directory

that's why and how to fix it?

thanks.

![image](https://github.com/tryphotino/photino.Blazor/assets/4169744/1036df97-7978-44ba-928d-6b895d627efa)

**Comment by MikeYeager** [comment]
@kingsonchan We're working on documentation for packaging for Linux. Please stay tuned for that.

**Comment by philippjbauer** [comment]
The guide for publishing on all platforms is available as a sample in the Photino.Samples repository as a separate project. It includes a publish script and packaging templates that can be adapted for your specific situation.

Currently only available in the debug branch (as of 03/19/2024), lets find the rough edges together! :)
https://github.com/tryphotino/photino.Samples/tree/debug/Photino.PublishPhotino
