### ISSUE TITLE
BlazorSample canot work on ububtu22.04 

### ISSUE THREAD

**Issue by kimdiego2098** [tryphotino/photino.Blazor#121]
![image](https://github.com/tryphotino/photino.Blazor/assets/82756760/b7d48f74-66fa-459e-be15-ac01056273c1)

Always stuck in loading, unable to load blazer content

Release linux-64 using the (Photo.Blazor. Sample) project from the original warehouse

**Comment by kimdiego2098** [comment]
The reason is that net8 is not supported

**Comment by dcuccia** [comment]
But, will it be supported?
