### ISSUE TITLE
Not working with .Net 8 on Ubuntu 22.04? 

### ISSUE THREAD

**Issue by b12-144** [tryphotino/photino.Blazor#123]
Hi, I cloned this repository and tried to run `Photino.Blazor.Sample` on Ubuntu 22.04 using dotnet SDk 8.0.105 (8.0.5 runtime), but it only displays `Loading...` . 
![Screenshot](https://github.com/tryphotino/photino.Blazor/assets/69040894/ccac1fe3-ded3-4b0f-9e36-e2254c28b34e)
Am I missing something? 

Also, If I run it on Wayland, it's possible to resize the window, but under X the window has no size and I could only show it with `.SetMaximized(true)`. 
Thanks, 
  Bruno.

**Comment by Andersen27** [comment]
I have the same problem with HelloWorld sample and my Photino-based projects.
I publish application on Windows with argument `--os linux` and copy output directory to Ubuntu 22.04.
Everything is working fine when i rolled back to commit 0422492d8a3cd848a04e5d3c5fe0778171be7111. Something broke after it.

![image](https://github.com/tryphotino/photino.Blazor/assets/44272176/98f01c90-3d36-4ffc-a74e-30841da52657)

**Comment by Tomiscout** [comment]
Same problem, also webkit dev tools don't work. Started occurring on 3.0.11, but 2.7.0 is still fine.

**Comment by kimdiego2098** [comment]
the same problem

**Comment by MikeYeager** [comment]
We release new 3.1.x versions yesterday with many fixes. It seems there were bugs using the new interop features in .NET 7 and 8. .NET 6 did not have the issues. In any case, please try the new versions and let us know if the issues persist.

**Comment by kimdiego2098** [comment]
@MikeYeager  3.1.8 version The bug still exists during testing , Same problem

**Comment by MikeYeager** [comment]
We have identified the issue and are working to resolve it.

**Comment by Jinjinov** [comment]
I know that this doesn't solve your problem, but my .NET 8 Photino Blazor app runs in Ubuntu 22.04

https://github.com/Jinjinov/OpenHabitTracker

![image](https://github.com/user-attachments/assets/dff38aed-5a14-471b-8e87-58500ed26ca8)

**Comment by ortega-01** [comment]
Update the Photino.Blazor package to its latest version (3.1.9) and the issue should resolve.
