### ISSUE TITLE
Linux on-screen keyboard

### ISSUE THREAD

**Issue by greatawesome** [tryphotino/photino.Blazor#125]
Does Photino on Linux have a on-screen keyboard, or does a developer need to create their own? I'm trying see if Photino would be a good platform for building a touchscreen application on an embedded device.

**Comment by MikeYeager** [comment]
@greatawesome We use GTK for Linux UI which does not include an on-screen keyboard. You would have to create your own. I believe there are some HTML/JavaScript/CSS libraries available for that.
