### ISSUE TITLE
Problem with Blazored Modal

### ISSUE THREAD

**Issue by peerem** [tryphotino/photino.Blazor#13]
We get this error, if we open a "Blazored Modal" window. It runs fine in Blazor WebAssembly, Blazor Server full or running on Chromely.

https://github.com/Blazored/Modal

![BlazoredModal](https://user-images.githubusercontent.com/73072999/111037160-3dc56300-8423-11eb-9e79-685ba2b55da9.PNG)

**Comment by peerem** [comment]
I found the problem. When debugging in Visual Studio, you do not copy the content files from third-party packages into the debug folder. You can also see this in the browser console:

Failed to load resource: net::ERR_NAME_NOT_RESOLVED https://app/_content/Blazored.Modal/blazored.modal.js

The published release version works without any problems. Everything is copied.

**Comment by MikeYeager** [comment]
Thanks for the post. Please join the discussion on #18

**Comment by ottodobretsberger** [comment]
It appears that this might be an issue with Visual Studio settings, of the 3rd party library files not set to copy to the output folder.
We will add something about it to our FAQ section in our documentation, but we aren't sure we can add a blanket solution to this kind of issue that applies to all possible 3rd party libraries.

**Comment by peerem** [comment]
Did you read that?

**The published release version works without any problems. Everything is copied.**

This third party library was just an example and works in every other scenario (WASM, pure Server, Chromely) so I don't think it's a library problem!

**Comment by MikeYeager** [comment]
Thank you for the additional comments. We believe this is related to #20 which includes suggested work-arounds. Please continue the conversation there if you have additional comments.
