### ISSUE TITLE
NuGet package only references photino.NET 3.1.17

### ISSUE THREAD

**Issue by MathiasLui** [tryphotino/photino.Blazor#140]
Current NuGet version still causes the linux error described at #126 - After removing the package reference and instead referencing the newest `photino.Blazor` master (with `3.1.18`) as a project, it works  

I assume that's not supposed to be? Or when are package updates pushed?

**Comment by MikeYeager** [comment]
@MathiasLui We are about to release a new version. We have been fixing some last minute issues.
