### ISSUE TITLE
Shows white screen while loading WebView2 component

### ISSUE THREAD

**Issue by svetovid** [tryphotino/photino.Blazor#142]
During application startup before `index.html` loaded, the window is just white. 
It would be nice to change its color, or even set a splashscreen.

On my Windows 10 computer, I have Dark theme enabled  
![Screenshot 2024-10-29 094550](https://github.com/user-attachments/assets/9ea182fd-cc2d-4da3-aee8-4b759d6813ed)

But, while I'm waiting for the web content (presumably, waiting for WebView2 to be loaded), the window is white

![Screenshot 2024-10-29 094750_2](https://github.com/user-attachments/assets/cc61039e-1774-4d06-8635-b4092355e09a)

When index.html downloaded, the Dark theme is applied

![Screenshot 2024-10-29 094817_2](https://github.com/user-attachments/assets/5333024b-e638-46f4-8488-b5d11cc70b0c)

Please, advise how to make the window black or set a splashscreen, because I didn't find anything useful in the library API

**Comment by evandrofadul** [comment]
I have the same question. I am migrating my WPF Blazor Hybrid application to Photino, but in Blazor Hybrid running on Windows it is possible to make the screen transparent using the environment variable:
```csharp
Environment.SetEnvironmentVariable("WEBVIEW2_DEFAULT_BACKGROUND_COLOR", "0");
```
However, this did not have the same effect in Photino, and I am looking for an alternative.

**Comment by evandrofadul** [comment]
I tried using the 2 commands below, but I was unsuccessful
```csharp
app.MainWindow.SetBrowserControlInitParameters("--cast-app-background-color=00000000");
```
```csharp
app.MainWindow.SetBrowserControlInitParameters("--default-background-color=00000000");
```

I also used other commands to test, but apparently none of them affected Chrome. I'm not sure if I used the commands correctly.

**Comment by MikeYeager** [comment]
We've been debugging through this and it appears the issue is not with the WebView2 browser control. What you're seeing is the background of the native window. We can't get it to follow the current theme. We can set it to a specific color on startup, but that's not a great solution. We would love some help from a Win32 expert. @Raxdiam, is this something you could help us with?

**Comment by MikeYeager** [comment]
UPDATE: We are now able to detect light and dark mode in Windows, even when it's changed as the app is running. We are setting the background of the window to either white or black accordingly. It's not a perfect solution as it doesn't pick up any actual background colors and can only be set to black or white. It does appear that on Windows, the browser control remains transparent. Setting a background color in HTML overrides any window background color we set. This will be available in the next release.

**Comment by evandrofadul** [comment]
That's great, thank you for your response. I’m looking forward to the next release!
