### ISSUE TITLE
`NavigationManager.NavigateTo` does not work in Photino.Blazor App when component is in a razor dll

### ISSUE THREAD

**Issue by Smurf-IV** [tryphotino/photino.Blazor#16]
The Razor Dll is shared between a "Normal Client" Dev hosted blazor app and a Photino App.

The pages are displayed from the Razor dll in both apps as expected. (i.e `AdditionalAssemblies` is working).

But using `NavigationManager.NavigateTo` to go directly to another page in the dll **does not work** in the photon app, but does in the Dev Studio Host

**Comment by ottodobretsberger** [comment]
For repro purposed we would need some more information about the running OS, the steps taken to trigger the error, etc.
More detail or a code sample would help us with that investigation.

**Comment by Smurf-IV** [comment]
Windows 10 Pro / Ent
Just Call `NavigationManager.NavigateTo` as you would in any other Blazor App !

**Comment by ottodobretsberger** [comment]
Similar to my response in #17, this might have to do with the internal version of Blazor in the Photino.Blazor project, which has not been updated from 3.1 to .NET 5 yet.
As we are currently working on that update, we will check back to this issue afterwards.

**Comment by tomlm** [comment]
I have rewritten Photino.Blazor to use Microsoft.AspNetCore.Components.WebView which is the library that backs MAUI, WPF, WinForm Blazor pages.  

You can see in the new sample it supports Page navigations.

Here is the PR: #29

**Comment by MikeYeager** [comment]
Photino.Blazor is now updated to use .NET 6.  @Smurf-IV Please try it out and let us know if you still have issues.
