### ISSUE TITLE
How do you refer to component _content ?

### ISSUE THREAD

**Issue by tomlm** [tryphotino/photino.Blazor#20]
For example, blazorize normally has HTML like this:

    \<link href="\_content/Blazorise/blazorise.css" rel="stylesheet" />  
 

But it's not found when loading.  I tried using \`\`\`http://app/\_content/blazorise/blazorise.css\`\`\` with no luck.  Am I missing something obvious?

**Comment by MikeYeager** [comment]
@tomlm Have you checked to see that the file (or the bundled file) is included in the build output folder? <project folder>\bin\Debug\net5.0\ ? If you're using Visual Studio, check the properties of the file and make sure it's set to 'copy if newer' or 'copy always'. Please let us know if this doesn't solve it.

**Comment by tomlm** [comment]
Yeah, it's more complicated then that...blazor components have _content folders which get placed into the wwwroot\_content\{packageId} folder as part of the build process.
See https://blazor-university.com/component-libraries/
My blazor asp.net project has 
```
\Server\obj\Release\net5.0\PubTmp\Out\wwwroot\_content
<DIR>          Blazorise
<DIR>          Blazorise.Bootstrap
<DIR>          BlazorMonaco
<DIR>          BlazorMonacoYaml
```
But my photino project doesn't have any _content folder from component packages output as of the build.

**Comment by MikeYeager** [comment]
@tomlm Thank you for the additional information. This is something we expect to be resolved when we update our Blazor source code, however this is out of our hands until then. We don't yet have a timeline for that, but we haves started the process. The problem is part of the build and deploy process which we don't have direct control over. However, we can suggest some work-arounds. In the Post-Build steps of the project properties, you can enter a COPY command to copy the _content folder into the output wwwroot folder. That's basically all the build and deploy changes will do. A slicker, but much more involved work-around can be found in this post: https://github.com/dotnet/aspnetcore/issues/13103#issuecomment-555172130 taken from the Blazor team's effort to solve this problem.

**Comment by tomlm** [comment]
By perusing the MAUI code base I found this and it seems to pull in all Blazor Component static dependencies!

With this change all "_content/{nuget}/{statifFile}" are resolved correctly.

Add this to your .cpsroj
```
 <!-- from https://github.com/dotnet/MobileBlazorBindings/blob/eaee277ee15fd3ef20f465c213bf6cd840023336/src/Microsoft.MobileBlazorBindings.WebView.Windows/build/Microsoft.MobileBlazorBindings.WebView.Windows.targets -->
        <Target Name="_StaticWebAssetsComputeFilesToBuild" AfterTargets="GetCopyToOutputDirectoryItems" DependsOnTargets="ResolveStaticWebAssetsInputs">
                <ItemGroup>
                        <!-- Filter the static web assets foreign to the project and then add them to the list of resolvedfiles to publish. -->
                        <_ExternalBuildStaticWebAsset Include="%(StaticWebAsset.FullPath)" Condition="'%(SourceType)' != ''">
                                <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
                                <TargetPath>$([MSBuild]::MakeRelative('$(MSBuildProjectDirectory)','$([MSBuild]::NormalizePath('wwwroot\%(BasePath)\%(RelativePath)'))'))</TargetPath>
                        </_ExternalBuildStaticWebAsset>
                        <!-- Remove any existing external static web asset that might have been added as part of the regular publish pipeline. -->
                        <_SourceItemsToCopyToOutputDirectory Remove="@(_ExternalBuildStaticWebAsset)" />
                        <_SourceItemsToCopyToOutputDirectory Include="@(_ExternalBuildStaticWebAsset)" />
                </ItemGroup>
        </Target>
```

**Comment by MikeYeager** [comment]
@tomlm Is this issue ready to close then?

**Comment by tomlm** [comment]
Yes, Microsoft.AspNetCore.WebView + Photino.Blazor correctly resolves _content paths

**Comment by grofit** [comment]
Sorry to re-raise this but im having this issue and it doesnt look like I can plop the above msbuild target bit into my csproj as it cant seem to find the related before/after targets (my photino blazor project is using `<Project Sdk="Microsoft.NET.Sdk">`.

I am trying to import a library which does the `_content` trick but nothing seems to get put in the debug/output, I am using Photino.Blazor 2.1.7.

As mentioned I have tried adding the above bit to my csproj and even pulled in the whole snippet from the source url it was taken from but it just tells me:

>   Process finished with exception The target "ResolveStaticWebAssetsInputs" does not exist in the project.  whatever.csproj

**Comment by grofit** [comment]
I managed to get this working but in the end it only works for `build` scenarios i.e `dotnet build` and doesnt output the `_content` for `dotnet publish` scenarios, its a bit of a pain really but I think my original problem was down to the `Project Sdk` not being the same as the one being used with the example above.
