### ISSUE TITLE
Photino.Blazor and Photino.Blazor.JS out of sync in the Debug branch

### ISSUE THREAD

**Issue by budcribar** [tryphotino/photino.Blazor#21]
@philippjbauer  The debug branch of Photino.Blazor.JS has been updated to  aspnetcore/main:2afcac2d152 which is out of sync with the following packages used by Photino.Blazor

<PackageReference Include="Microsoft.AspNetCore.Components" Version="5.0.3" />
 <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="5.0.3" />
 <PackageReference Include="Microsoft.JSInterop" Version="5.0.3" />

The aspnetcore/webjs files in Photino.Blazor.JS should come from the same major version as the packages in Photino.Blazor since there are interdependent.

It looks to me that aspnetcore/main:2afcac2d152 corresponds to the v.6.0.0-preview3 versions of the Microsoft.AspNetCore.Components, Microsoft.AspNetCore.Components.Web,Microsoft.JSInterop

I suggest that we have a 6.0 branch for Photino.Blazor which pulls the webjs files from the latest 6.0 prelease tag and have the debug branch pull the webjs files from the 5.0.5 tag.   

p.s. I have been working on leveraging the Photino.Blazor project. (See https://github.com/budcribar/RemoteBlazorWebView and
https://github.com/budcribar/RemotePhotino.NET )

**Comment by philippjbauer** [comment]
Well observed. We've been trying to upgrade the Blazor.JS contents according to the instructions left by Steve Sanderson. Unfortunately the upgrade to a newer version hasn't been successful and the debug branch. I opted to reset the branch to its previous state today, with the exception of a newer debug Photino.NET debug version.

Hope that fixes the immediate issue of the broken build for you. The pipeline ran successfully again at least.

**Comment by budcribar** [comment]
Resetting the branch to its previous state is a step in the right direction. However, there are still some incompatibilities between the main branch of Photino.Blazor.JS  (You are using the 3.x version of Blazor.JS from Steve Sanderson) and the 5.03 revision of Microsoft.AspNetCore.Components, Microsoft.AspNetCore.Components.Web,Microsoft.JSInterop. What you really need to do is to take the webjs file from the 5.0.5 tag and use 5.0.5 of Microsoft.AspNetCore.Components, Microsoft.AspNetCore.Components.Web,Microsoft.JSInterop.  Then also apply the necessary changes in Photino.Blazor.

I have done this in the https://github.com/budcribar/RemotePhotino.NET repository. However there is some additional functionality to allow users to create an application which can be remotely controlled. I can help you out if needed.

**Comment by MikeYeager** [comment]
We're about to run some tests of Photino Blazor against .NET 6 MAUI with full-sized web view control to see if there are advantages to us continuing with Blazor support in Photino.

**Comment by budcribar** [comment]
I think the main advantage is that Linux users cannot currently use either the WPF or WinForms Blazor controls and Blazor Photino is their only choice.

The latest preview4 changed the way the JS and Control interact again, so you will need to track closely those changes if you want to continue supporting Blazor Photino.

I am committed to supporting a remoteable version of the Wpf control and shortly the Windows form control so I can take over supporting a version using the WebWindow for those users on Linux if you guys want to drop support for Photino, or I can help you if merge  in the appropriate changes.

**Comment by MikeYeager** [comment]
After some initial tests, it's clear that, although the tooling and documentation isn't ready yet, .NET 6 MAUI with Blazor is going to do a great job of replacing Photino eventually. It's small, fast and backed by Microsoft. Of course, it won't be released until November and currently there are issues running it on all platforms (tooling issues more than anything). Microsoft has not announced when they'll incorporate Linux support, though they say it's planned. Other factors include that it requires a Xamarin (MAUI) setup to support the full-screen WebView control which adds a little complexity to the source code, but doesn't seem to add much overhead. We still plan on releasing a new version of Photino as soon as we can get it finished and tested that will add some much needed features. It's till the way to go if you need cross-platform that includes Linux and it doesn't require a somewhat tricky setup process of VS 2019 preview, special NuGet package sources, etc...

**Comment by tomlm** [comment]
I really hope you reconsider.  MAUI comes with a ton of baggage and doesn't support linux. Photino is the promised land...

**Comment by tomlm** [comment]
I have rewritten Photino.Blazor to use **Microsoft.AspNetCore.Components.WebView** which is the library that backs MAUI, WPF, WinForm Blazor pages.  

Here is the PR: https://github.com/tryphotino/photino.Blazor/pull/29

Can we revisit Blazor support :)

**Comment by MikeYeager** [comment]
Photino.Blazor is now updated to use .NET 6 and all branches are in sync.
