### ISSUE TITLE
InputFile OnChange event not firing

### ISSUE THREAD

**Issue by markrendle** [tryphotino/photino.Blazor#22]
There's an open issue on the Samples repo (https://github.com/tryphotino/photino.Samples/issues/11) about this, but it should be on this repo.

The `OnChange` callback for the `InputFile` component does not get called in Photino. Is there any chance of a fix or are you done with Blazor support?

**Comment by MikeYeager** [comment]
@markrendle With the .NET 6 Previews getting closer to an RTM version, we'd like to try creating some sample MAUI "hybrid" apps that use a MAUI window with a full-sized web view control to see how it stacks up against Photino. They're still not release-bits, but it will give us a better indication of what the advantages and disadvantages of each approach are. If we can't add a lot of value, then it's probably not worth creating a competing product.
