### ISSUE TITLE
Is there a way to switch DI provider like in typical ASP builders?

### ISSUE THREAD

**Issue by grofit** [tryphotino/photino.Blazor#23]
So for example in a default Blazor WASM or Server project I can change the underlying DI system to something else, such as:

```csharp
public static async Task Main(string[] args)
{
	var builder = WebAssemblyHostBuilder.CreateDefault(args);
	// ...
	var container = new Container(); // DryIoc Container
	builder.ConfigureContainer(new DryIocServiceProviderFactory(container));
	// ...
}
```

The builder available for Photino doesn't seem to support changing of, so just wondering if this is on purpose and if not could it be supported?

**Comment by MikeYeager** [comment]
We don't have any builders specific to Photino. We use standard .NET builders for things like hosting WebAPI endpoints, etc. in our examples. Perhaps we're not understanding the question? Photino is a console application that creates a native Window on the appropriate operating system using C and C++ code.

**Comment by grofit** [comment]
Sure, but the Blazor flavour must wrap the way Blazor resolve `@inject` calls etc at some point right? be it through the stuff in .net core ASP framework or through some other mechanism.

In typical Blazor (or asp) apps you can tell it to replace the default `Microsoft.DependencyInjection.Extensions` (may not be actual name of it) with some other DI framework. So in ours we use DryIoC for resolving (As we have some non trivial DI concerns we cannot express through the built in MS one).

**Comment by tomlm** [comment]
I have rewritten Photino.Blazor to use Microsoft.AspNetCore.Components.WebView which is the library that backs MAUI, WPF, WinForm Blazor pages.  This properly handles _content without csproj

It supports the Builder pattern, although it doesn't have .ConfigureContainer it's probably not hard to add

Here is the PR: #29
