### ISSUE TITLE
Can I run the app if installed in Program Files?

### ISSUE THREAD

**Issue by matthewfitzmaurice** [tryphotino/photino.Blazor#25]
I've created a new Photino.Blazor app using the HelloPhotino template in Visual Studio 2019. I can run this fine from my development folder. However it does not run when published to a Program Files folder.

Can anyone explain why this is so? Is it because files are downloaded and Program Files is read-only?

**Comment by MikeYeager** [comment]
@matthewfitzmaurice There was a change in V2 that moves the default location of temp files for the WebView2 control from Program Files (with the app), to the appropriate temp folder and also allows the developer to override that path if desired. We just merged a pull request for an updated version of the Blazor package (which we don't officially support, but contributors are continuing to work on). Once we do some minimal testing on it, we will release a V2 version of the Blazor package which will fix this issue for you.
