### ISSUE TITLE
How to access IServiceProvider?

### ISSUE THREAD

**Issue by NewMySQL** [tryphotino/photino.Blazor#33]
I ran into a problem when porting code to Photino.Blazor. there are no features that the "Startup.Configure" function brings.

More specifically, I need to get an ILoggerFactory instance for further configuration.

Theoretically, I could achieve a similar result of the "Startup.Configure" function if I were to access "IServiceProvider", but looking at the sources I saw that "IServiceProvider" has private.

I suggest how to fix it

1) In PhotinoBlazorApp class
```
public IServiceProvider Services { get; private set; }

internal void Initialize(IServiceProvider services, RootComponentList rootComponents)
{
    Services = services;
    ...
}
```

2) In PhotinoBlazorAppBuilder class
```
public PhotinoBlazorApp Build(Action<IServiceProvider> action = null)
{
    ...
    action?.Invoke(sp);
    ...
}
```

**Comment by tomlm** [comment]
Take a look at new pattern which uses a builder with .Services for dI.

```C#
namespace Photino.Blazor.MudBlazorSample
{
    class Program
    {
        [STAThread]
        static void Main(string[] args)
        {
            var appBuilder = PhotinoBlazorAppBuilder.CreateDefault(args);

            appBuilder.Services
                .AddLogging();

            // register root component and selector
            appBuilder.RootComponents.Add<App>("app");

            var app = appBuilder.Build();

            // customize window
            app.MainWindow
                .SetTitle("Photino.Blazor MudBlazor Sample");

            AppDomain.CurrentDomain.UnhandledException += (sender, error) =>
            {
                app.MainWindow.OpenAlertWindow("Fatal exception", error.ExceptionObject.ToString());
            };

            app.Run();

        }
    }
}
```

**Comment by NewMySQL** [comment]
I am using the new template. But you probably did not understand the essence of the problem. "PhotinoBlazorAppBuilder.Service" provides access to "IServiceCollection" but I need to access "IServiceProvider" which can be accessed after calling "IServiceCollection.BuildServiceProvider" function.

Here is an example of what I want to achieve, like in asp.net 6.0
```csharp
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddLogging(); // Services type is IServiceCollection

var app = builder.Build();

var loggerfactory = app.Services.GetService<ILoggerFactory>(); // Services type is IServiceProvider

app.Run();
```

**Comment by tomlm** [comment]
oh got it, that makes sense.
