### ISSUE TITLE
Native System API

### ISSUE THREAD

**Issue by Denny09310** [tryphotino/photino.Blazor#44]
Hi, I would need to know how to access the system API such as selecting a path to write / read a file. Since the update to .net 6, the System.Windows.Form namespace has been removed and there does not appear to be a method for opening native dialogs in Photino.Blazor (other than MessageBoxes). I tried to implement a third party library in C by myself ([this one](https://github.com/mlabbe/nativefiledialog)), but it keeps crashing and giving me error on EmbeddedWebView.dll. In case a method to access the system API is not already implemented, would anyone be willing to help me implement the library I was talking about? (I don't know C well)

PS: Can we label this issue as Question?

**Comment by ottodobretsberger** [comment]
We do not currently have support for native file dialogues yet. Any dialogues for that matter. But we would be happy to see community involvement around that and see if this feature could get added.
Also, you could probably just use the browser's file dialogue, couldn't you?

**Comment by Denny09310** [comment]
Yes I tried to use the browser system. the problem is that I had to use some weird methods, such as, for example, force the https in the WebView via the schema and ignore SSL errors. this worked on windows but with the linux/osx "app: //" scheme it doesn't allow me to use it, because it can only be used in a sicure contex

**Comment by Denny09310** [comment]
> We do not currently have support for native file dialogues yet. Any dialogues for that matter. But we would be happy to see community involvement around that and see if this feature could get added. Also, you could probably just use the browser's file dialogue, couldn't you?

Yes I tried to use the browser system. the problem is that I had to use some weird methods, such as, for example, force the https in the WebView via the schema and ignore SSL errors. this worked on windows but with the linux/osx "app: //" scheme it doesn't allow me to use it, because it can only be used in a sicure contex

**Comment by NoahStolk** [comment]
I'd also be interested in a feature like this. My current approach is to declare an interface:

```cs
public interface INativeFileSystemService
{
	FileResult? OpenFile(string? extensionFilter);

	void SaveDataToFile(byte[] data);

	string? SelectDirectory();

	public record FileResult(string Path, byte[] Contents);
}
```

Then implement that interface for Windows and Linux, and register it in Program.cs according to the running operating system:

```cs
PhotinoBlazorAppBuilder appBuilder = PhotinoBlazorAppBuilder.CreateDefault(args);
appBuilder.Services.AddLogging(builder => builder.AddConsole());

#if WINDOWS
appBuilder.Services.AddSingleton<INativeFileSystemService, WindowsFileSystemService>();
#elif LINUX
appBuilder.Services.AddSingleton<INativeFileSystemService, LinuxFileSystemService>();
#endif

// ...
```

I only have the "open file" functionality for Windows at the moment.

```cs
public class WindowsFileSystemService : INativeFileSystemService
{
	public INativeFileSystemService.FileResult? OpenFile(string? extensionFilter)
	{
		OpenFileName ofn = new()
		{
			filter = extensionFilter, // Split by null-terminating \0, or the window will crash. Example: "Log files\0*.log\0Batch files\0*.bat\0",
			file = new(new char[256]),
			maxFile = 256,
			fileTitle = new(new char[64]),
			maxFileTitle = 64,
			initialDir = "C:\\",
			title = "Open file",
		};
		ofn.structSize = Marshal.SizeOf(ofn);

		if (!NativeMethods.GetOpenFileName(ofn) || ofn.file == null)
			return null;

		return new INativeFileSystemService.FileResult(ofn.file, File.ReadAllBytes(ofn.file));
	}

	// ...
}
```

P/Invoke Comdlg32.dll:

```cs
[DllImport("Comdlg32.dll", CharSet = CharSet.Auto)]
internal static extern bool GetOpenFileName([In, Out] OpenFileName ofn);

[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Auto)]
public class OpenFileName
{
	public int structSize;
	public IntPtr dlgOwner = IntPtr.Zero;
	public IntPtr instance = IntPtr.Zero;

	public string? filter;
	public string? customFilter;
	public int maxCustFilter;
	public int filterIndex;

	public string? file;
	public int maxFile;

	public string? fileTitle;
	public int maxFileTitle;

	public string? initialDir;

	public string? title;

	public int flags;
	public short fileOffset;
	public short fileExtension;

	public string? defExt;

	public IntPtr custData = IntPtr.Zero;
	public IntPtr hook = IntPtr.Zero;

	public string? templateName;

	public IntPtr reservedPtr = IntPtr.Zero;
	public int reservedInt;
	public int flagsEx;
}
```

It's not pretty, but it does the job.

**Comment by philippjbauer** [comment]
@NoahStolk thanks for that contribution. In another issue (https://github.com/tryphotino/photino.NET/issues/22) a user pointed us to a project that can handle file dialogs cross-platform. We're curious about this project and want to try it out in Photino. @Denny09310 Perhaps that is a way forward and something you want to take a look at as well.

**Comment by philippjbauer** [comment]
Closing the issue here in Blazor to continue the discussion in the .NET project.
Please refer to the following issue: https://github.com/tryphotino/photino.NET/issues/22
