### ISSUE TITLE
Possible to get Photino to accept external http connections for api endpoints?

### ISSUE THREAD

**Issue by grofit** [tryphotino/photino.Blazor#58]
I cant think of anywhere better to ask this so apologies if this is not the best place.

I have a scenario where I have a basic application which needs to handle an OAuth flow (as well as some other web based scenarios) which require us to have a web host running to accept external connections.

Internally Photino is running a webserver its just not exposed externally as 0.0.0.0 is not resolvable, so is there a way to also piggyback on top of the existing builder and add the required `MVC` bits in etc?

Currently im side loading another webserver via the .net 6 `WebApplicaiton.CreateBuilder` approach, but the problem I have here is that they do not share the same `IServiceCollection` instances so any dependencies are isolated between each host, so an `IEventBus` within the controllers cant talk to the `IEventBus` within the Photino world.

I also need to manage its lifecycle separately to the Photino one, which isnt a massive problem but it is extra overhead.

**Comment by MikeYeager** [comment]
@grofit Photino does not run its own web server. It just runs a browser control. That said, many of our samples DO also run the ASP.NET Core web server to provide a service layer. It is not required however and not part of Photino. The basic means of communication between the browser control and the .NET wrapper (or any other 3rd party wrapper for that matter), is passing strings via memory buffer.

**Comment by grofit** [comment]
Yeah I can run a separate web host alongside photino fine, its just they do not share the same underlying `IServiceCollection` which causes issues for me, I have worked around it using a Service Location approach :( on the web host side.

I had incorrectly assumed photino was running a barebones webserver internally or something, thanks for getting back to me though.
