### ISSUE TITLE
Wrapping Photino in another app? [general question]

### ISSUE THREAD

**Issue by somelinguist** [tryphotino/photino.Blazor#73]
Hi, I really like Photino, especially Photino. Blazor. Thanks for all your work on it. 

I know that Photino is focused on making cross platform desktop apps with web technology, but I was wondering if it were also possible to embed it or part of it in other apps as well to be able to use native controls for some parts of an app.

Some background: A few months ago I wrote an Eto.Forms control that wraps BlazorWebView. I wanted it to work on macOS (not catalyst), WPF/ WinForms, and eventually GTK. I got the control working well for a hobby F# app I’m working on (the control is in C#).

The WPF/WinForms controls wrap the official ones, while macOS is adapted from the MAUI iOS one. I also looked at your implementation for Photino for inspiration.

Eto.Forms itself can also target Linux via GTK, but I don’t know really where to begin for getting BlazorWebView to work for it.

That’s where my interest in whether it would be possible to wrap Photino (or part of it) comes in.

Again, I know that’s not your focus, but thought it wouldn’t hurt to ask.

If not, do you have any ideas of how it might be possible to go about supporting BlazorWebView on Linux? I’ve found a few other places on GitHub discussing this, but haven’t been able to figure it out (some links in the repo below). If not, no worries. :)

The repo for my control with a couple examples is here: https://github.com/somelinguist/Eto.Blazor It's probably a bit out of date with the official BlazorWebView controls. It's also lacking some features.

Thanks again for making Photino!

**Comment by ottodobretsberger** [comment]
Hello! Thank you for your interest!
I am not entirely sure of a use case where Photino (a wrapper essentially for WebView2) would need to be wrapped again for various operating systems. I believe maybe extending the current implementation on a Photino Native level would align more with the goals you have set.
Additionally, Photino is written in a way where the window (and subsequent windows) are generated on a native OS level, which would make it very hard to keep it 'wrapped' within another technology.

I saw there exists the [Eto.HtmlRenderer](https://www.nuget.org/packages/Eto.HtmlRenderer) , which you could use to display your html content (Blazor?) in ETO without the need to embed Photino. Or maybe I am not understanding the full picture, and if that's the case, you could illustrate your undertaking with a few more details and we will see if we can help.

**Comment by somelinguist** [comment]
Hello. Thanks so much for your reply and feedback. 

Mostly I’m looking at trying to wrap BlazorWebView on more desktop platforms for an app that would still make use of native controls where it makes sense too.




The app I’m working on now only really needs a webview for one of the main controls. The control let’s a user edit multilingual interlinear-glossed texts. HTML seems to provide the best way to work with and layout such content.

But using wrapped native controls for other parts of the app seems to provide a more pleasant/easier to implement experience (native menus, split panels, toolbars, etc). Eto Forms provides a nice way to do that across desktop platforms. Looking at your goals, it seems some of those (like menus) might eventually come to Photino, but not all (understandably).

I initially started looking into BlazorWebView because it seemed it would provide the best way to communicate across web and native controls. Eto.Forms also provides a a that wraps WebView2 and WkWebkit, but communicating between it and other controls is a bit more indirect.

I’ve been able to successfully wrap BlazorWebView for WPF/WinForms and macOS targets in Eto.Forms (not WinUI or MacCatalyst as in MAUI).

I’ve looked into getting it to work for GTK targets in Eto as well, but it seems a lot more complicated. Part of it is just my unfamiliarity with GTK. :)

As far as I can tell, Photino is the only project to have successfully wired up BlazorWebView to the webview in GTK. 

I’ve tried looking through your code to find all of the relevant parts, but still not sure I’ve found them all. I’ve already noticed that parts of it would first require wrapping more GTK function calls than Eto.Forms currently does, which shouldn’t be to much of an issue apart from making sure to get all the right ones. 

I was asking about wrapping Photino mostly because you’ve already abstracted hooking BlazorWebView to the underlying webview. I was hoping it might be possible to wrap your abstracted webview in Eto. But now I see it looks like it goes through the Photino window to the webview rather than just the webview, which makes perfect sense for Photino’s goals. But wouldn’t be a good fit for wrapping in something like Eto.Forms. 

For my own project, I’ve started looking at whether it would be simpler to communicate across controls just using Eto.Forms’ webview with JS and catching navigation events without using Blazor, or even just wrapping a lightweight server.

But I still find the prospect of having BlazorWebView wrapped and able to interact with native controls on more desktop platforms to be an interesting pursuit. :)

Thanks again for your help!
