### ISSUE TITLE
question: Is there a way to have a multi-window Photino.Blazor app with a single PhotinoBlazorApp instance?

### ISSUE THREAD

**Issue by gnalvesteffer** [tryphotino/photino.Blazor#88]
For example, if I want to have a single set of services, app state, etc, with multiple windows presenting different kinds of information/views, how can I do that? From my research and experimentation so far, it seems like I have to create a separate PhotinoBlazorApp instance per window, which doesn't satisfy the aforementioned requirements. It looks like `PhotinoBlazorApp` and its underlying components are tightly coupled to a single window experience.

A specific use-case I have is to have a shared Fluxor state between windows on a multi-display system, driving different presentations off of the same app state, which propagates seamlessly from any updates.

**Comment by gnalvesteffer** [comment]
I have a workaround, and after some more thought, I think the current design of the PhotinoBlazorApp makes sense. I realized that all I really needed to share was my Fluxor state, and in order to do so with multiple Fluxor instances, I kept track of all of the PhotinoBlazorApp instances and dispatched actions across all of their registered Fluxor `IDispatcher`s using my own "PropagatedDispatcher" class that abstracts this.

**Comment by charleypeng** [comment]
hi, i am using blazor as well, and can you give a sample about how to open a razor page in a new window? many thanks!

**Comment by charleypeng** [comment]
hi, i am using blazor as well, and can you give a sample about how to open a razor page in a new window? many thanks!

**Comment by gnalvesteffer** [comment]
> hi, i am using blazor as well, and can you give a sample about how to open a razor page in a new window? many thanks!

Hi, the way I'm doing it at the moment is by wrapping the window creation operations in my own `CreateWindow` method with the following signature:
```c#
private static void CreateWindow<TRootComponent>(
            WindowInfo windowInfo,
            Action? onWindowCreated = null
        ) where TRootComponent : IComponent
```

`TRootComponent` would be the Razor page/component that gets rendered in your html's "app" element, e.g.:
```c#
appBuilder.RootComponents.Add<TRootComponent>("app");
```

`WindowInfo` is just a class I made that holds the window title, and HTML path, among other details specific to my application.
I use `windowInfo.HtmlPath` to set the startup page for the window like so:
```c#
app.MainWindow
                .Load(new Uri(windowInfo.HtmlPath, UriKind.Relative))
```

and then register a window created event handler for the MainWindow, and have it invoke my `onWindowCreated` action parameter, which I use to create the next window via another `CreateWindow` call (since `CreateWindow` is blocking due to `app.Run()`). There's likely a cleaner way to do this, but this works for me for now.

**Comment by charleypeng** [comment]
Cool, will try it later, thanks!

**Comment by gnalvesteffer** [comment]
One thing to note is that the `app.MainWindow.Load()` method doesn't work with the current photino.Blazor release (v2.6.0).
`.Load()` was fixed in a recent commit and is pending a proper release. I currently reference the photino.Blazor project directly in my solution pointed to master with this fix.

**Comment by charleypeng** [comment]
> One thing to note is that the `app.MainWindow.Load()` method doesn't work with the current photino.Blazor release (v2.6.0); the URL passed to it isn't respected and will always use index.html.
> `.Load()` was fixed in a recent commit and is pending a proper release. I currently reference the photino.Blazor project directly in my solution pointed to master with this fix.

hi gnalvesteffer, i did what you just wrote above into my code, but not work as expected, so any code showcase would be greate!  thanks!

**Comment by charleypeng** [comment]
I have got my application working in this case and opened 2 windows, but both of them are in a loading state and no blazor component rendered.

`class Program
    {
        [STAThread]
        static void Main(string[] args)
        {

            CreateWindow<App>(new WindowInfo("wwwroot/index.html"), () =>
            {
                CreateWindow<Rock>(new WindowInfo("wwwroot/index2.html"));
            });
        }

        private static void CreateWindow<TRootComponent>(
            WindowInfo windowInfo,
            Action? onWindowCreated = null) where TRootComponent: IComponent
        {
            var appBuilder = PhotinoBlazorAppBuilder.CreateDefault();
            appBuilder.Services
               .AddLogging();

            // register root component
            appBuilder.RootComponents.Add<TRootComponent>("app");
            var app = appBuilder.Build();

            // customize window

            app.MainWindow.SetTitle(windowInfo.Title);


            
            app.MainWindow.Load(windowInfo.HtmlPath);

            app.MainWindow.RegisterWindowCreatedHandler((s, e) =>
            {
                onWindowCreated?.Invoke();
            });

            app.Run();
        }

    }`

**Comment by charleypeng** [comment]
it is odd that by removing  app.MainWindow.Load(windowInfo.HtmlPath) the two windows are just working!  i did what you said by just reference the latest Photino code, no clue about this

**Comment by gnalvesteffer** [comment]
Hey @charleypeng, I'll put together a more comprehensive code sample in a bit.

**Comment by gnalvesteffer** [comment]
@charleypeng I created a PR to add a sample multi-window application here: https://github.com/tryphotino/photino.Blazor/pull/90

See if this works for you.

**Comment by charleypeng** [comment]
> @charleypeng I created a PR to add a sample multi-window application here: https://github.com/tryphotino/photino.Blazor/pull/90
> 
> 
> 
> See if this works for you.

That's great thanks!

**Comment by Andersen27** [comment]
What is missing is the ability to specify a parent window so that child windows stack in the OS opened windows panels, rather than being displayed as two separate applications. Maybe need to make PhotinoWindow.Parent property writable?
@MikeYeager
