### ISSUE TITLE
System.AccessViolationException: ref/xxx.dll

### ISSUE THREAD

**Issue by DavidDXY** [tryphotino/photino.Blazor#9]
follow the document,I download the PhotinoSamples.vsix file and Create a Photino.Blazor Demo,when I debug project It show the Error message :
![image](https://user-images.githubusercontent.com/28525559/110482396-9a730600-8123-11eb-82f7-c969b73c4dfb.png)

**Comment by DavidDXY** [comment]
by the way the Photino.Blazor Version is 1.0.7

**Comment by tylerwp** [comment]
Getting the same error when setup from VS and command line. Run as administrator did not help. 
"Attempted to read or write protected memory. This is often an indication that other memory is corrupt."

exception | {"Attempted to read or write protected memory. This is often an indication that other memory is corrupt."} | System.AccessViolationException

**Comment by MikeYeager** [comment]
We are in the process of updating our project templates and samples. Please try updating your Photino.Blazor NuGet package to 1.1.1 (posted about an hour ago) and let us know if that solves the problem for you. We believe it will.

**Comment by tylerwp** [comment]
Thanks @MikeYeager working for me now!🎆
