### ISSUE TITLE
Missing Blazor template

### ISSUE THREAD

**Issue by mocox** [tryphotino/photino.Blazor#91]
Hi, I was trying to create a new blazor project but t is missing from the templates when installed from the cli on linux, or do i have to do something else?

<pre>
...
NUnit 3 Test Item                             nunit-test               [C#],F#,VB  Test/NUnit                          
NUnit 3 Test Project                          nunit                    [C#],F#,VB  Test/NUnit                          
Photino Samples HelloPhotino Static File ...  photinostaticfileserver  [C#]        Photino/html/fileserver/CORS/Desktop
Photino Samples HelloPhotino3d                photino3d                [C#]        Photino/html/3d/Desktop             
Photino Samples HelloPhotino3dReact           photino3dreact           [C#]        Photino/html/3d/ReactJS/Desktop     
Photino Samples HelloPhotinoAngular           photinoangular           [C#]        Photino/html/Angular/Desktop        
Photino Samples HelloPhotinoApp               photinoapp               [C#]        Photino/html/Desktop                
Photino Samples HelloPhotinoGrpc              photinogrpc              [C#]        Photino/html/gRPC/Desptop           
Photino Samples HelloPhotinoMultiWindow       photinomultiwindow       [C#]        Photino/html/Desktop                
Photino Samples HelloPhotinoReact             photinoreact             [C#]        Photino/html/React/Desktop          
Photino Samples HelloPhotinoTestBench         photinotestbench         [C#]        Photino/html/Desktop                
Photino Samples HelloPhotinoVue               photinovue               [C#]        Photino/html/Vue/VueJS/Desktop      
Protocol Buffer File                          proto                                Web/gRPC                            
Razor Class Library                           razorclasslib            [C#]        Web/Razor/Library                   
...
</pre>

Thanks

**Comment by josago97** [comment]
I don't think there is a template for Blazor, but it would be great if there was.

**Comment by josago97** [comment]
I have created a [PR](https://github.com/tryphotino/PhotinoSamples.VSExtension/pull/6) to add a template for Photino applications with Blazor WebAssembly.

**Comment by philippjbauer** [comment]
Closed with https://github.com/tryphotino/PhotinoSamples.VSExtension/pull/6
