### ISSUE TITLE
Maximized bool broken?

### ISSUE THREAD

**Issue by IceReaper** [tryphotino/photino.Blazor#96]
```csharp
private void Maximize()
{
	App.MainWindow.SetMaximized(!App.MainWindow.Maximized);
}
```

This should be a simple toggle function. However, the Maximized bool always returns false, hence the window going into maximized mode, and never back.

OS: Manjaro KDE Linux (all updates installed)
Hardware: Thinkpad T14, intel iris xe, intel i7, 32gb ram.

**Comment by MikeYeager** [comment]
Thanks for the report. We've actually encountered this on Linux and will look into it. We've been putting in hours on several new features and bug fixes and will try to resolve this.

**Comment by MikeYeager** [comment]
This should be fixed in the latest versions of Photino. Please re-open if this is still an issue.
