### ISSUE TITLE
.net 8 suppport

### ISSUE THREAD

**Issue by hi-xiaoxin** [tryphotino/photino.Blazor#98]
I am a loyal .NET developer and I really like photino.Net. I have tried using .NET 8 but it is not working properly. In our company's use case, .NET 8  'Blazor United' is the most suitable choice and we urgently need to upgrade to .NET 8. Could you provide support?

**Comment by MikeYeager** [comment]
@hi-xiaoxin Can you tell us what's not working properly? We haven't spent any time on .NET 8 yet since it's still not released.

**Comment by hi-xiaoxin** [comment]
@MikeYeager 

When using .NET8 RC2, you may encounter some dependency injection errors similar to the following:

```  
System.InvalidOperationException:“Cannot provide a value for property 'ScrollToLocationHash' on type 'Microsoft.AspNetCore.Components.Routing.Router'. There is no registered service of type 'Microsoft.AspNetCore.Components.Routing.IScrollToLocationHash'.”  
```

We have conducted some tests and only need to add .NET 8 dependency.

``` c#

	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
		<PackageReference Include="Microsoft.AspNetCore.Components.WebView" Version="6.0.10" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
		<PackageReference Include="Microsoft.AspNetCore.Components.WebView" Version="7.0.1" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Microsoft.AspNetCore.Components.WebView" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
	</ItemGroup>
```

Additionally, after updating to .NET 8 RC2, the example Photino.Blazor.NativeAOT is not working properly after being published, which is likely caused by publish trimming.

Thanks.

**Comment by MikeYeager** [comment]
@hi-xiaoxin We have just finished testing updating Photino.NET and Photino.Blazor to run .NET 6, 7 or 8 (previously only 6 and 7 were supported). All of our tests completed with no errors except AOT compilation. We don't use ScrollToLocationHash in any of our code, so I'm not sure where that error comes from. On our AOT test, we get the runtime error: "Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll", which we will look into. Is ScrollToLocationHash something you're injecting in your code?

**Comment by ourplan9000** [comment]
Cannot provide a value for property 'ScrollToLocationHash' on type 'Microsoft.AspNetCore.Components.Routing.Router'. There is no registered service of type 'Microsoft.AspNetCore.Components.Routing.IScrollToLocationHash'.
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
 .NET 8

**Comment by ourplan9000** [comment]
<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Microsoft.AspNetCore.Components.WebView" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
	</ItemGroup>

**Comment by En3Tho** [comment]
I think `QuickGrid` might use that under the covers. I have the same problem in .Net8

**Comment by MikeYeager** [comment]
@En3Tho Thanks for the update! The .NET team has said that AOT support is "a journey" and that anything that makes use of reflection will likely be a problem. So far, we have only seen issues in .NET 8 with AOT. Is anyone having issues aside from AOT?

**Comment by hi-xiaoxin** [comment]
.NET 8 + MudBlazor

```
System.InvalidCastException:“Unable to cast object of type 'Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager' to type 'Microsoft.AspNetCore.Components.WebView.Services.WebViewNavigationManager'.”

Microsoft.AspNetCore.Components.WebView.PageContext..ctor(Dispatcher dispatcher, AsyncServiceScope serviceScope, IpcSender ipcSender, JSComponentConfigurationStore jsComponentsConfiguration, String baseUrl, String startUrl)
Microsoft.AspNetCore.Components.WebView.WebViewManager.<AttachToPageAsync>d__21.MoveNext()
Microsoft.AspNetCore.Components.WebView.IpcReceiver.<OnMessageReceivedAsync>d__2.MoveNext()
Microsoft.AspNetCore.Components.WebView.WebViewManager.<>c__DisplayClass18_0.<<MessageReceived>b__0>d.MoveNext()
Microsoft.AspNetCore.Components.WebView.IpcSender.<>c__DisplayClass12_0.<NotifyUnhandledException>b__1()
Photino.Blazor.PhotinoDispatcher.InvokeAsync(Action workItem) 
Microsoft.AspNetCore.Components.WebView.IpcSender.NotifyUnhandledException(Exception exception)
Microsoft.AspNetCore.Components.WebView.WebViewManager.<>c__DisplayClass18_0.<<MessageReceived>b__0>d.MoveNext()
```

**Comment by anan1213095357** [comment]
> @MikeYeager
> 
> When using .NET8 RC2, you may encounter some dependency injection errors similar to the following:
> 
> ```
> System.InvalidOperationException:“Cannot provide a value for property 'ScrollToLocationHash' on type 'Microsoft.AspNetCore.Components.Routing.Router'. There is no registered service of type 'Microsoft.AspNetCore.Components.Routing.IScrollToLocationHash'.”  
> ```
> 
> We have conducted some tests and only need to add .NET 8 dependency.
> 
> ```cs
> 	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
> 		<PackageReference Include="Microsoft.AspNetCore.Components.WebView" Version="6.0.10" />
> 		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0" />
> 	</ItemGroup>
> 	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
> 		<PackageReference Include="Microsoft.AspNetCore.Components.WebView" Version="7.0.1" />
> 		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
> 	</ItemGroup>
> 	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
> 		<PackageReference Include="Microsoft.AspNetCore.Components.WebView" Version="8.0.0" />
> 		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
> 	</ItemGroup>
> ```
> 
> Additionally, after updating to .NET 8 RC2, the example Photino.Blazor.NativeAOT is not working properly after being published, which is likely caused by publish trimming.
> 
> Thanks.



> Hi @MikeYeager
> 
> > Is ScrollToLocationHash something you're injecting in your code
> 
> Maybe is MudBlazor.

他这个是web自带框架的一个东西 你自己写一个接口实现类注入进去就行了，我这边注入成功了，但是提示不支持 联合渲染模式。

**Comment by grofit** [comment]
Just to mention I am hitting this now when trying to update a .net 6 app to .net 8

**Comment by MikeYeager** [comment]
We are currently testing with .net 8 and should release that soon. Please re-open if the next release does not fix the issue.

**Comment by ivanjx** [comment]
@MikeYeager is a fix out yet? if not when can we expect one? thanks!

**Comment by philippjbauer** [comment]
@ivanjx Photino.NET 2.6.0 and Photino.Blazor 2.7.0 were just released with .NET8 support. I tried to publish the NativeAOT sample on my Mac but it failed. I saw you mention the AOT issue I experienced here: https://github.com/tryphotino/photino.Blazor/issues/94#issuecomment-1858811885. I will spin this into its own Issue so we can track it better.

**Comment by grofit** [comment]
I have just updated to this latest version and I am back to getting the white screen issue, in the previous version I could manually include the WebView nuget but even with that its still just showing the empty/white screen on load.
