### ISSUE TITLE
Add minimal apior controller

### ISSUE THREAD

**Issue by franklupo** [tryphotino/photino.Blazor#99]
Hi,
great work. Would it be possible to use controller or minimal api?

best regards

**Comment by MikeYeager** [comment]
@franklupo While we do have a sample (Server sample) that demonstrates loading ASP.NET Core as a server, but it's not part of Photino. We see no reason why you couldn't use controllers or minimal api there. Photino.Native is a C++ native window with a native web control. Photino.NET is a .NET wrapper that creates and communicates with the native window. It doesn't contain any ASP.NET Core unless you add it like we did in the sample.

**Comment by franklupo** [comment]
> @franklupo While we do have a sample (Server sample) that demonstrates loading ASP.NET Core as a server, but it's not part of Photino. We see no reason why you couldn't use controllers or minimal api there. Photino.Native is a C++ native window with a native web control. Photino.NET is a .NET wrapper that creates and communicates with the native window. It doesn't contain any ASP.NET Core unless you add it like we did in the sample.

my problem is with a web authentication then I have to redirect a page that presents data both with sockets. How can I do?
